from override import override

class X: ...
class Y(X): ...
class Z(Y): ...

class Base:
  def f(self) -> Y: ...
  def g(self) -> Y: ...
  def h(self) -> Y: ...

  def i(self, x: Y): ...
  def j(self, x: Y): ...
  def k(self, x: Y): ...

  def l(self, x): ...
  def m(self, x): ...
  def n(self, x): ...
  def o(self, x, *args): ...
  def p(self, x, *args): ...

  def q(self, *, x): ...
  def r(self, *, x): ...
  def s(self, *, x): ...
  def u(self, **kwargs): ...
  def v(self, **kwargs): ...

class Middle(Base): ...

class Derived(Middle):
  @override
  def f(self) -> Y: ...
  @override
  def g(self) -> Z: ...
  @override
  def h(self) -> X: ...

  @override
  def i(self, x: Y): ...
  @override
  def j(self, x: Z): ...
  @override
  def k(self, x: X): ...

  @override
  def l(self): ...
  @override
  def m(self, x): ...
  @override
  def n(self, x, y): ...
  @override
  def o(self, x): ...
  @override
  def p(self, x, *args): ...
  
  @override
  def q(self, *, x): ...
  @override
  def r(self, *, y): ...
  @override
  def s(self): ...
  @override
  def u(self): ...
  @override
  def v(self, *, x, **kwargs): ...
  
  @override
  def w(self): ...

Derived().f() # OK
Derived().g() # OK
Derived().h() # Failed, return type mismatch (X > Y)

Derived().i(Z()) # OK
Derived().j(Z()) # Failed, parameter x type mismatch (Y > Z)
Derived().k(X()) # OK

Derived().l(1) # Failed, parameter counter mismatch (1 < 2)
Derived().m(1) # OK
Derived().n(1) # Failed, parameter counter mismatch (3 > 2)
Derived().o(1) # Failed, *args presence mismatch
Derived().p(1) # OK, parent signature has *args, allow more positional parameters

Derived().q(x = 1) # OK
Derived().r(x = 1) # Failed, keyword only parameter name mismatch (`x` vs. `y`)
Derived().s(x = 1) # Failed, keyword only parameter count mismatch
Derived().u(x = 1) # Failed, **kwargs presence mismatch
Derived().v(x = 1) # OK, parent signature has **kwargs, allow more keyword only parameters

Derived().w() # Failed, w does not override any methods
