from override import override

class X: ...
class Y(X): ...
class Z(Y): ...

class Base:
  def f(self) -> Y: ...
  def g(self) -> Y: ...
  def h(self) -> Y: ...

  def i(self, x: Y): ...
  def j(self, x: Y): ...
  def k(self, x: Y): ...

  def l(self, x, y, *args): ...
  def m(self, x): ...
  def n(self, *, x, y, **kwargs): ...
  def o(self, *, x, **kwargs): ...
  def p(self, x, *args): ...

  def q(self, *, x): ...
  def r(self, *, x): ...
  def s(self, *, x): ...
  def u(self, **kwargs): ...
  def v(self, **kwargs): ...

class Middle(Base): ...

class Derived(Middle):
  @override
  def f(self) -> Y: ...
  @override
  def g(self) -> Z: ...
  @override
  def h(self) -> X: ...

  @override
  def i(self, x: Y): ...
  @override
  def j(self, x: Z): ...
  @override
  def k(self, x: X): ...

  @override
  def l(self, x): ...
  @override
  def m(self, x, extra=0): ...
  @override
  def n(self, *, x): ...
  @override
  def o(self, *, x, extra=0, **kwargs): ...
  @override
  def p(self, x, extra=0, *args): ...
  
  @override
  def q(self, *, x): ...
  @override
  def r(self, *, y): ...
  @override
  def s(self): ...
  @override
  def u(self): ...
  @override
  def v(self, *, x, **kwargs): ...
  
  @override
  def w(self): ...

Derived().f() # OK
Derived().g() # OK
Derived().h() # Failed, return type mismatch (X > Y)

Derived().i(Z()) # OK
Derived().j(Z()) # Failed, parameter x type mismatch (Y > Z)
Derived().k(X()) # OK

Derived().l(1) # OK, *args allows the child to omit trailing positional parameters
Derived().m(1) # OK, extra positional parameter has a default
Derived().n(x = 1) # OK, **kwargs allows the child to omit keyword-only parameters
Derived().o(x = 1) # OK, extra keyword-only parameter has a default
Derived().p(1) # OK, extra positional parameter has a default

Derived().q(x = 1) # OK
Derived().r(x = 1) # Failed, keyword only parameter name mismatch (`x` vs. `y`)
Derived().s(x = 1) # Failed, keyword only parameter count mismatch
Derived().u() # OK, parent has **kwargs and the child can omit keyword-only parameters
Derived().v(x = 1) # Failed, child cannot have extra keyword parameter with no default value

Derived().w() # Failed, w does not override any methods
